version: '3'
services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    container_name: recommendarr
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Enable CORS if needed
      # - ENABLE_CORS=true
      # - CORS_ORIGIN=http://example.com
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped
